### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by antonklava** [timlindeberg/rapidjson-LLDB-Formatters#1]
This is looking really handy and I would like to use this in one of my projects.

However I noticed that this is missing a LICENSE file and before I can take this any further I was wondering if you would mind adding one? This contains some more information: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository

Thanks

**Comment by timlindeberg** [comment]
Sorry for the super late reply on this, just saw your message. I've gone ahead and added a license file! :)

**Comment by antonklava** [comment]
Thank you!
